#!/bin/bash

# Extract the node version of image that is being built e.g. 3.30.6-node22 builds an image based on node:22-alpine
# For the latest tag we default to node 22
if [[ $DOCKER_TAG =~ ^[0-9a-zA-Z.]+-node([0-9.]+)$ ]]; then 
  VERSION=${BASH_REMATCH[1]}
elif [[ $DOCKER_TAG == 'latest' ]]; then
  VERSION='22'
else
  echo 'Unsupported tag.'
  exit 1;
fi

docker build --build-arg NODE_TAG="$VERSION-alpine" -f $DOCKERFILE_PATH -t $IMAGE_NAME .
